language: julia

matrix:
  include:
    - os: linux
    - os: osx

julia:
  - 1.0.0

install:
  - julia -e 'using Pkg;Pkg.add("Conda")'
  - julia -e 'using Conda;Conda.add("matplotlib==2.0.1")'
  - julia -e 'using Pkg;Pkg.add("PyCall")'
  - julia -e 'using Pkg;ENV["PYTHON"]="";Pkg.build("PyCall")'
  - julia -e 'using Pkg;Pkg.add("Coverage")'
  - julia deps/build.jl

script:
  #- julia test/runtests.jl
  - julia --code-coverage test/runtests.jl

after_success:
  # for coveralls
  - julia -e 'using Coverage; Coveralls.submit(process_folder())'

